/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group2;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Admin
 */
public class Final extends javax.swing.JFrame {
    Connection con = null;
    /**
     * Creates new form Final
     * 
     * 
     */
     public Final() {
        initComponents();
        con = DBConnect.connect();
        txtid.setVisible(false);
    }
    
   
    
    public void fetch(){
        txtid.setEnabled(false);
        txtproduct.setEnabled(false);
        txtqty.setEnabled(false);
        cmdadd.setEnabled(true);
        cmdsave.setEnabled(false);
        cmdedit.setEnabled(true);
        cmdupdate.setEnabled(false);
        cmddelete.setEnabled(true);
        cmdexit.setText("Exit");
        tbl1.setEnabled(true);
        try {
            
            PreparedStatement ps = con.prepareStatement("select * from inventory order by id asc");

            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                String id = String.valueOf(rs.getInt("id"));
                String product = rs.getString("product");
                String qty = rs.getString("qty");
                
                txtid.setText(""+id);
                txtproduct.setText(product);
                txtqty.setText(""+qty);
               
                
                
                String tbData[] = {id,product,qty};
                    DefaultTableModel tblModel = (DefaultTableModel)tbl1.getModel();
                    tblModel.addRow(tbData);
                    
                
            
            }

        } catch (Exception ex) {
            Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void fetch2(){
        txtid.setEnabled(false);
        txtproduct.setEnabled(false);
        txtqty.setEnabled(false);
        cmdadd.setEnabled(true);
        cmdsave.setEnabled(false);
        cmdedit.setEnabled(true);
        cmdupdate.setEnabled(false);
        cmddelete.setEnabled(true);
        cmdexit.setText("Exit");
        tbl1.setEnabled(true);
        try {
            
            PreparedStatement ps = con.prepareStatement("select * from inventory order by id asc");

            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                String id = String.valueOf(rs.getInt("id"));
                String product = rs.getString("product");
                String qty = rs.getString("qty");
                
                txtid.setText(""+id);
                txtproduct.setText(product);
                txtqty.setText(""+qty);
               
                
                
                String tbData[] = {id,product,qty};
                    DefaultTableModel tblModel = (DefaultTableModel)tbl1.getModel();
                    tblModel.addRow(tbData);
                    tblModel.setRowCount(0);
                
            
            }

        } catch (Exception ex) {
            Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        cmdadd = new javax.swing.JButton();
        cmdedit = new javax.swing.JButton();
        cmdexit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        cmddelete = new javax.swing.JButton();
        cmdsearch = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmdsave = new javax.swing.JButton();
        cmdupdate = new javax.swing.JButton();
        txtcategory = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtproduct1 = new javax.swing.JTextField();
        txtproduct2 = new javax.swing.JTextField();
        txtproduct3 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product");

        Category.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Category.setForeground(new java.awt.Color(255, 255, 255));
        Category.setText("Category");

        cmdadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdadd.setForeground(new java.awt.Color(0, 102, 102));
        cmdadd.setText("ADD");
        cmdadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdaddActionPerformed(evt);
            }
        });

        cmdedit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdedit.setForeground(new java.awt.Color(0, 102, 102));
        cmdedit.setText("EDIT");
        cmdedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditActionPerformed(evt);
            }
        });

        cmdexit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdexit.setForeground(new java.awt.Color(0, 102, 102));
        cmdexit.setText("EXIT");
        cmdexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdexitActionPerformed(evt);
            }
        });

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTS", "QTY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl1);

        cmddelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmddelete.setForeground(new java.awt.Color(0, 102, 102));
        cmddelete.setText("DELETE");
        cmddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeleteActionPerformed(evt);
            }
        });

        cmdsearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdsearch.setForeground(new java.awt.Color(0, 102, 102));
        cmdsearch.setText("Search");
        cmdsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsearchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search");

        cmdsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdsave.setForeground(new java.awt.Color(0, 102, 102));
        cmdsave.setText("SAVE");
        cmdsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsaveActionPerformed(evt);
            }
        });

        cmdupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdupdate.setForeground(new java.awt.Color(0, 102, 102));
        cmdupdate.setText("UPDATE");
        cmdupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdupdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtsearch)
                                .addGap(18, 18, 18)
                                .addComponent(cmdsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmddelete, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                .addComponent(cmdexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(cmdupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cmdedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmdsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdadd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Category)
                                .addGap(45, 45, 45))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtproduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtproduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category)
                    .addComponent(txtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtproduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdadd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdsave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdedit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cmdexit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdaddActionPerformed
        txtid.setText("");
        txtproduct.setText("");
        txtqty.setText("");
        cmdexit.setText("CANCEL");
        cmdedit.setEnabled(false);
        cmdsave.setEnabled(true);
        cmdadd.setEnabled(false);
        cmdupdate.setEnabled(false);
        cmdsearch.setEnabled(false);
        cmddelete.setEnabled(false);
        tbl1.setEnabled(false);
        txtid.setEnabled(false);
        txtproduct.setEnabled(true);
        txtqty.setEnabled(true);
        
        

    }//GEN-LAST:event_cmdaddActionPerformed

    private void cmdeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditActionPerformed

        cmdexit.setText("CANCEL");
        cmdadd.setEnabled(false);
        cmdsearch.setEnabled(false);
        cmddelete.setEnabled(false);
        cmdsave.setEnabled(false);
        cmdupdate.setEnabled(true);
        cmdedit.setEnabled(false);
        tbl1.setEnabled(false);
        txtid.setEnabled(true);
        txtproduct.setEnabled(true);
        txtqty.setEnabled(true);
        
        
    }//GEN-LAST:event_cmdeditActionPerformed

    private void cmdexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdexitActionPerformed
        if(cmdexit.getText().equals("CANCEL")){
            cmdexit.setText("EXIT");
            cmdsave.setEnabled(false);
            cmdupdate.setEnabled(false);
            cmdadd.setEnabled(true);
            cmdedit.setEnabled(true);
            tbl1.setEnabled(true);
            txtid.setEnabled(false);
            txtproduct.setEnabled(false);
            txtqty.setEnabled(false);
        }else{
            Menu MenuFrame = new Menu();
           // FinalFrame.setVisible(true);
            MenuFrame.pack();
            MenuFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_cmdexitActionPerformed

    private void cmddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeleteActionPerformed
        String id = txtid.getText();
        int result = JOptionPane.showConfirmDialog(this,"Do you want to delete this record","Confirmation",JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            try {
                    PreparedStatement ps = con.prepareStatement("delete from inventory where id = ?");
                    ps.setString(1,id);
                    ps.executeUpdate();


                } catch (Exception ex) {
                    Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
                }
            JOptionPane.showMessageDialog(this,"Deleted Successfully");
            fetch2();
            fetch();
            
        }
    }//GEN-LAST:event_cmddeleteActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        int row = tbl1.getSelectedRow();
        String tc = tbl1.getModel().getValueAt(row, 0).toString();
        try {
            
            PreparedStatement ps = con.prepareStatement("select * from inventory where id="+tc+" ");

            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                int id = rs.getInt("id");
                String product = rs.getString("product");
                int qty = rs.getInt("qty");
               
                
                txtid.setText(""+id);
                txtproduct.setText(product);
                txtqty.setText(""+qty);
               
                
            }

        } catch (Exception ex) {
            Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void cmdsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsearchActionPerformed
       
        txtid.setEnabled(false);
        txtproduct.setEnabled(false);
        txtqty.setEnabled(false);
        cmdadd.setEnabled(true);
        cmdsave.setEnabled(false);
        cmdedit.setEnabled(true);
        cmdupdate.setEnabled(false);
        cmddelete.setEnabled(true);
        cmdexit.setText("Exit");
        tbl1.setEnabled(true);
        String products = txtsearch.getText();
        try {
            
            PreparedStatement ps = con.prepareStatement("select * from inventory where product = ? order by id asc");
            ps.setString(1,products);

            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                String id = String.valueOf(rs.getInt("id"));
                String product = rs.getString("product");
                String qty = rs.getString("qty");
                
                txtid.setText(""+id);
                txtproduct.setText(product);
                txtqty.setText(""+qty);
                
                String tbData[] = {id,product,qty};
                    DefaultTableModel tblModel = (DefaultTableModel)tbl1.getModel();
                    tblModel.addRow(tbData);   
                    
            }

        } catch (Exception ex) {
            Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
        }
        fetch2();
        
        
    }//GEN-LAST:event_cmdsearchActionPerformed

    private void cmdsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsaveActionPerformed
       
            int result = JOptionPane.showConfirmDialog(this,"Do you want to add this record?","Confirmation",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                try {
                    String product = txtproduct.getText();
                    String qty = txtqty.getText();

                    PreparedStatement ps = con.prepareStatement("insert into inventory(product,qty) values(?,?)");
                    ps.setString(1,product);
                    ps.setString(2,qty);

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Insert Successful");
                    fetch();

                } catch (Exception ex) {
                    Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        fetch2();
        fetch();
    }//GEN-LAST:event_cmdsaveActionPerformed

    private void cmdupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdupdateActionPerformed
        int result = JOptionPane.showConfirmDialog(this,"Do you want to update this record","Confirmation",JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            try {
                String id = txtid.getText();
                String product = txtproduct.getText();
                String qty = txtqty.getText();

                PreparedStatement ps = con.prepareStatement("update inventory set product = ?,qty = ? where id = ?");
                ps.setString(1,product);
                ps.setString(2,qty);
                ps.setString(3, id);
                ps.executeUpdate();
                

            } catch (Exception ex) {
                Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this,"Updated Successfully");
            fetch2();
            fetch();
        }
    }//GEN-LAST:event_cmdupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdadd;
    private javax.swing.JButton cmddelete;
    private javax.swing.JButton cmdedit;
    private javax.swing.JButton cmdexit;
    private javax.swing.JButton cmdsave;
    private javax.swing.JButton cmdsearch;
    private javax.swing.JButton cmdupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtproduct1;
    private javax.swing.JTextField txtproduct2;
    private javax.swing.JTextField txtproduct3;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
